"""add_sensor_to_device_types

Revision ID: 28f6d91e5b8d
Revises: 25dc1a6ad142
Create Date: 2025-04-03 15:45:12.873501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28f6d91e5b8d'
down_revision: Union[str, None] = '25dc1a6ad142'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
